import React from 'react';
import { Globe, Cpu, Radio, ShieldCheck, Database, Server, AlertCircle } from 'lucide-react';

export type ProvenanceTier = 
  | 'LIVE_NCPOR'
  | 'REAL_NCPOR'
  | 'PHYSICS_MODEL'
  | 'PHYSICS_SYNTHETIC'
  | 'SYNTHETIC_SIMULATION'
  | 'SIMULATED'
  | 'PUBLIC_EXTERNAL'
  | 'REAL_PUBLIC'
  | 'EDGE_CACHE'
  | 'EDGE_SIMULATED'
  | 'EXTERNAL_ANTARCTIC_BENCHMARK'
  | 'DERIVED'
  | 'OFFLINE'
  | 'MOCK'
  | string;

interface Props {
  type: ProvenanceTier;
  provider?: string;
  size?: 'sm' | 'md';
  className?: string;
}

export const ProvenanceBadge: React.FC<Props> = ({ 
  type, 
  provider, 
  size = 'sm', 
  className = '' 
}) => {
  const norm = (type || 'MOCK').toUpperCase().trim();

  let label = 'PROVENANCE UNKNOWN';
  let Icon = Database;
  let color = 'bg-slate-900 text-slate-400 border-slate-700';
  let tooltip = 'Data provenance unverified.';

  if (norm === 'LIVE_NCPOR' || norm === 'REAL_NCPOR' || norm === 'LIVE') {
    label = 'LIVE • NCPOR';
    Icon = ShieldCheck;
    color = 'bg-emerald-950/80 text-emerald-300 border-emerald-500/40';
    tooltip = 'Live physical station telemetry from NCPOR / MoES AWS observing systems.';
  } else if (norm === 'PHYSICS_MODEL' || norm === 'PHYSICS_SYNTHETIC') {
    label = 'PHYSICS MODEL';
    Icon = Cpu;
    color = 'bg-cyan-950/80 text-cyan-300 border-cyan-500/40';
    tooltip = 'First-principles thermodynamic differential model. Causal coupling of ambient wind-chill, thermal loss, and fuel burn.';
  } else if (norm === 'SYNTHETIC_SIMULATION' || norm === 'SIMULATED' || norm === 'SIMULATION') {
    label = 'SYNTHETIC SIMULATION';
    Icon = Cpu;
    color = 'bg-purple-950/80 text-purple-300 border-purple-500/40';
    tooltip = 'Deterministic contingency simulation model. Generated by the POLAR-TWIN What-If Engine.';
  } else if (norm === 'PUBLIC_EXTERNAL' || norm === 'REAL_PUBLIC') {
    label = 'PUBLIC DATA';
    Icon = Globe;
    color = 'bg-blue-950/80 text-blue-300 border-blue-500/40';
    tooltip = 'Public atmospheric and oceanographic satellite observation (CMEMS / Open-Meteo Antarctic Grid).';
  } else if (norm === 'EXTERNAL_ANTARCTIC_BENCHMARK') {
    label = 'ANTARCTIC BENCHMARK';
    Icon = Globe;
    color = 'bg-amber-950/80 text-amber-300 border-amber-500/40';
    tooltip = 'Isolated external Antarctic operational dataset (AADC Davis Station) used for calibration.';
  } else if (norm === 'EDGE_CACHE' || norm === 'EDGE_SIMULATED') {
    label = 'EDGE CACHE';
    Icon = Radio;
    color = 'bg-sky-950/80 text-sky-300 border-sky-500/40';
    tooltip = 'Station edge gateway local store-and-forward buffer with CRC-32 integrity validation.';
  } else if (norm === 'DERIVED') {
    label = 'DERIVED METRIC';
    Icon = Server;
    color = 'bg-slate-800 text-slate-300 border-slate-600';
    tooltip = 'Calculated derived engineering metric based on verified station sensor inputs.';
  } else if (norm === 'OFFLINE') {
    label = 'OFFLINE DATA';
    Icon = AlertCircle;
    color = 'bg-rose-950/80 text-rose-300 border-rose-500/40';
    tooltip = 'Telemetry from edge buffer during satellite carrier disruption.';
  }

  const padding = size === 'sm' ? 'px-2 py-0.5 text-[10px]' : 'px-2.5 py-1 text-xs';
  const iconSize = size === 'sm' ? 'w-2.5 h-2.5' : 'w-3.5 h-3.5';

  return (
    <div
      title={tooltip}
      className={`inline-flex items-center gap-1.5 rounded font-mono tracking-wider uppercase border shadow-sm cursor-help transition-all hover:brightness-110 select-none ${padding} ${color} ${className}`}
    >
      <Icon className={`${iconSize} flex-shrink-0`} />
      <span className="font-semibold">{label}</span>
      {provider && (
        <span className="opacity-75 text-[9px] border-l border-current/30 pl-1.5">
          {provider}
        </span>
      )}
    </div>
  );
};
